### ISSUE TITLE
Unable to create workspace for a project in another collection than DefaultCollection

### ISSUE THREAD

**Issue by leo9223** [Microsoft/vso-intellij#24] opened 2016-09-28 06:08 UTC
![tfsasbug](https://cloud.githubusercontent.com/assets/8036332/18902385/21171a2e-856c-11e6-918b-95b34fff7d43.png)

This form hangs up if I used to create a workspace for a team project exist in another collection rather than DefaultCollection.

**Comment by leantk** [comment] 2016-09-28 18:10
Hi,

Thank for reporting the problem. I'm trying to reproduce this on my end and I do see an issue when I hit "Create Workspace". An error appears but I have to wait several minutes for it to happen (while I wait it looks like a hang has occurred). If you wait some time do you eventually see an error? If so could you paste that here please?

Also, if you wouldn't mind, it would be really helpful if I could get a log from you. If you follow the last FAQ at this link, it will give you the steps you need to get the log: http://java.visualstudio.com/Docs/tools/androidStudio#_frequently-asked-questions-faq

If you don't want to attach the log to this issue for privacy reasons, feel free to email it to me at leantk@microsoft.com

Thanks,
-Leah

**Comment by leo9223** [comment] 2016-09-30 05:19
Dear leantk,

I have seen the logs and I have found that it says DefaultCollection is not found 404 error. 

It only makes workspaces for the collections with the name DefaultCollection.

It is working with DefaultCollection but with no other collection name.

let me find the log

**Comment by leantk** [comment] 2016-10-04 13:22
@leo9223 could I get that log please? I need to see at what point it fails for the non-DefaultCollections.

**Comment by ogarvey** [comment] 2016-11-04 13:17
@leantk I'm getting the same error, I've attached a log that should show the point of failure.

First mention of TFS is at line 561

[idea.log.txt](https://github.com/Microsoft/vso-intellij/files/571568/idea.log.txt)

**Comment by leantk** [comment] 2016-11-08 18:19
Hi @ogarvey,

Thanks for the log. I'm looking into it right now. I wanted to confirm some facts with you to make sure I understand the situation correctly. Let me know if any of the following statements are incorrect:

* When you try to checkout from TFS, you see all your DefaultCollection repos but your repos from your custom collection do not show up
* You are trying to checkout a TFVC repo and not a Git repo
* You are using a server url to sign in that follow the format: http://<server-name>:<port>/tfs/ and not adding the collection name on the end

Thanks for your help,
-Leah

**Comment by ogarvey** [comment] 2016-11-14 10:40
Hi @leantk I'm not actually checking anything out, it's when trying to import an existing Android Studio project into TFVC

Server format is as per last line http://:/tfs/

**Comment by leantk** [comment] 2016-11-14 19:19
Oh I misunderstood your issue @ogarvey. My apologies. Currently, the plug-in does not have the ability to import existing TFVC projects into Team Services or TFS. Only Git repositories can be imported at this time. The TFVC functionality is new to the plug-in and we are still adding more support every sprint. Importing is on our list of things to add but we haven't reached it yet. Sorry for the inconvenience. A workaround that you could do is create a new empty TFVC repo in the browser and then checkout that repo in Android Studio. Once you have that, you can copy all you files over into that repo and check them in. I know that isn't ideal but it will unblock you so you don't have to wait for us to release the Import feature.

Thanks and let me know if you have anymore questions,
-Leah

**Comment by 00101010** [comment] 2016-12-07 12:29
Hi @leantk ,

I'm experiencing the same issue (freeze on [ Create Workspace ]).
- same 404 not found messages in the log file and 'endless' threadDumps-*.txt's - although I don't think the 404 not found messages are the source of the issue.

I debugged the plugin with the latest sources from GitHub and it always hangs when executing the following request (which btw works when pasting the URL into a browser):
https://***:8081/tfs/Dev/_apis/connectionData?connectOptions=IncludeServices&lastChangeId=-1&lastChangeId64=-1&api-version=1.0

last line before the freeze: org.apache.http.pool.PoolEntryFuture.java > await(...) > this.condition.wait() {Line Number 138}
Wireshark doesn't record the request and it seems to await forever.

I'll further investigate, but I thought this might help you narrow it down.

If you need any information, please don't hesitate to contact me.

Regards
Michael

**Comment by leantk** [comment] 2016-12-07 16:20
Hi @00101010,

Thanks for following up on this and taking the time to look into it yourself. Are you seeing this just in Android Studio or in IntelliJ as well? Could you send me a full log of your Create Workspace freeze please? My email address is leantk@microsoft.com if you don't want to attach here. The steps to get the log are here as the last FAQ: http://java.visualstudio.com/Docs/tools/intelliJ#_frequently-asked-questions-faq

Before you do that though, can you increase your memory for the IDE? That should fix the thread dump issue and clear up the logs so it's easier to read. This is a common issue many users have dealing with Android Studio in general. You can make the change by going to Help -> Edit Custom VM Options. Increase -Xms to 512m or 750m and -Xmx to 2048m. This does depend on your machine so if you're using something without a lot of memory, this won't be an option.

Thanks again,
-Leah

**Comment by 00101010** [comment] 2016-12-08 09:13
Hi @leantk,

Thank you for your reply. I see this with Android Studio and IntelliJ. I'll send you an email with the log file attachted.

Thank you for your help

Regards
Michael

**Comment by leantk** [comment] 2017-02-01 18:07
This has been followed up offline and the fix has been released. If you are still seeing the problem please feel free to repoen the issue.

**Closed by leantk** 2017-02-01 18:07 UTC
