### ISSUE TITLE
TFVC: Android Studio Honour tfignore

### ISSUE THREAD

**Issue by erikhubers** [Microsoft/vso-intellij#53] opened 2017-01-27 14:31 UTC
Hey there,

I noticed the Android Studio is constantly asking me to add files to TFS that I don't want to add to version control. It's not honouring the .tfignore file I configured to ignore certain files and placed alongside my build.gradle file. Is this a bug or isn't it supported yet?

![image](https://cloud.githubusercontent.com/assets/1276421/22374128/23cbb5f2-e4a5-11e6-8ebb-dbda80ae00ca.png)

**Comment by DavidStaheli** [comment] 2017-03-24 19:55
Hi @erikhubers, we've been unable to reproduce this.  I'll close the issue for now, but please re-open if you have additional info.  Thank you for reporting the problem.  We're anxious to fix it if we can.

**Closed by DavidStaheli** 2017-03-24 19:55 UTC
Labels: bug
