### ISSUE TITLE
cannot see the collections in tfs

### ISSUE THREAD

**Issue by SrivatsaMarichi** [Microsoft/vso-intellij#22] opened 2016-08-02 07:18 UTC
I have 5 collections in my onprem tfs. I want to stop couple of them say 3. And I wish to see the other 2 collections in my android studio while connecting. But unfortunately I cannot see any of them.

![1](https://cloud.githubusercontent.com/assets/13433045/17320093/46934c86-5881-11e6-8c3b-b5563d18a849.jpg)

**Comment by AlexRukhlin** [comment] 2016-08-02 13:32
Hi,

Could you please provide a bit more details regarding the situation? What are steps to reproduce the issue? Which version of the Android Studio and the VSO-IntelliJ plugin do you use?

Do I understand well that 
1. You stop some collection(s) in your TFS using TfsMgmt.exe program, after that
2. You Try to connect to the server using Android Studio?

Thanks,
Alex

**Comment by SrivatsaMarichi** [comment] 2016-08-02 13:40
Hi Alex,
The latest version of android studio (2.1) + latest version of intellij plugin is being used.Your understanding is correct. 
I stopped collection using Tfsmgmt.exe. But when i try to access the TFS for the other coollections, it doesn't appear.
Thanks,Srivatsa 

    On Tuesday, 2 August 2016 7:02 PM, Alex Rukhlin <notifications@github.com> wrote:
 

 Hi,Could you please provide a bit more details regarding the situation? What are steps to reproduce the issue? Which version of the Android Studio and the VSO-IntelliJ plugin do you use?Do I understand well that 
1. You stop some collection(s) in your TFS using TfsMgmt.exe program, after that
2. You Try to connect to the server using Android Studio?Thanks,
Alex—

**Comment by AlexRukhlin** [comment] 2016-08-03 13:23
Hi Srivasta,
That looks like a bug, I'm sorry to say. Apparently, an exception occurring when the plugin tries to access an offline collection crashes the plugin. Thanks for catching that issue.

The item is assigned to the dev. team.

Alex

**Comment by SrivatsaMarichi** [comment] 2016-08-03 17:37
Ohh, cool. Thanks for the heads up!

**Comment by leantk** [comment] 2016-08-04 13:17
Hi Srivasta,

Were you able to see any of your repositories before you stopped the 3 collections? Were any of those repositories in the collections you did not stop? 

To help us better take a look at this would you mind sending us a log of when you try to checkout a repository when you have the collections stopped and when you don't have the collections stopped? The instructions on how to turn on logging and find the log from Android Studio are in the last FAQ here: http://java.visualstudio.com/Docs/tools/androidstudio#_frequently-asked-questions-faq

You can send that to me directly if you would prefer not to post it here. My email is leantk@microsoft.com.

**Comment by SrivatsaMarichi** [comment] 2016-08-04 13:52
Hi Leah,

I was able to see all the repositories from within my Android Studio before stopping my collections in TFS. 
I have 6 Team Project Collections. 4 of them have Team Projects. Other 2 doesn't have Team Projects due to which i wasn't able to see those as well.

When i stop the collections (those without team projects) i cannot see the collections which were online. Please find the below zip file along with the log and screenshots for your reference.

Thanks,
Srivatsa



![s01_without stopping collection](https://cloud.githubusercontent.com/assets/13433045/17404240/af0f6706-5a78-11e6-8178-0a2a1f78c0d2.png)
![s02_afterstoppingtwoemptycollections](https://cloud.githubusercontent.com/assets/13433045/17404241/af1f312c-5a78-11e6-9d3b-b8105b4637e3.png)

**Comment by SrivatsaMarichi** [comment] 2016-08-04 13:53
[idea.txt](https://github.com/Microsoft/vso-intellij/files/401776/idea.txt)

**Comment by leantk** [comment] 2016-08-04 15:36
Hi Srivatsa,

I think I found a fix for your issue. I've attached an updated version of the plugin for you to try. Let me know how it goes. If it still doesn't work please let me know and I can look at the new logs. I added more logging as well so we can see what else might be happening. 
[plugin.idea-1.104.0.zip](https://github.com/Microsoft/vso-intellij/files/401987/plugin.idea-1.104.0.zip)

**Comment by SrivatsaMarichi** [comment] 2016-08-05 05:23
Hi Leah,

PFA log. The error still shows up when i stop the collections!
[idea.txt](https://github.com/Microsoft/vso-intellij/files/403178/idea.txt)

**Comment by leantk** [comment] 2016-08-05 13:22
I don't see my new logging in that log so try this build instead. Sometimes you need to bump the version number up for the change in the plugin to be detected. My mistake, I should have done that originally.
[plugin.idea-1.104.1.zip](https://github.com/Microsoft/vso-intellij/files/403815/plugin.idea-1.104.1.zip)

**Comment by SrivatsaMarichi** [comment] 2016-08-10 13:39
Hi Leah,

That didn't work though. PFA logs for the same.

[idea.txt](https://github.com/Microsoft/vso-intellij/files/411192/idea.txt)

**Comment by SrivatsaMarichi** [comment] 2016-08-11 05:13
Hi Leah,
Now that the collections show up upon stopping the collections. The updated plugin did work. Thanks a ton to the entire team for fixing up the issue and helping in resolve the problem :-)

Thanks,
Srivatsa

**Comment by leantk** [comment] 2016-08-15 13:48
Thanks for bringing the issue to our attention Srivatsa!

**Closed by leantk** 2016-08-15 13:48 UTC
