### ISSUE TITLE
android studio- VSTS fails to connect while using organizational network 

### ISSUE THREAD

**Issue by apsuch-cont** [Microsoft/vso-intellij#55] opened 2017-02-08 11:20 UTC
We are using android studio and the Microsoft managed VSTS Plugin to connect. This works fine when on an open internet connection however when connecting via out work proxy we are unable to connect. We can still access VSTS via a browser even through the proxy. Just the connect through the plugin does not work.

Our organisation uses ADFS authentication.

We have tried the following to no avail:
1. We tried adding proxy settings in Android studio as in system default proxy settings
2. we have tried adding ADFS SSL certificates to java JVM

Steps we followed in android studio.
1. changed proxy settings in android studio
![image](https://cloud.githubusercontent.com/assets/25635574/22734529/09684826-ee1c-11e6-8125-6f621c6a0542.png)
2. VCS->Import into version control->Import into team services Git..->on team services tab ->sign in
 when we enter organizayional user id it takes me to the organizational sign in page successfully.
![image](https://cloud.githubusercontent.com/assets/25635574/22734858/36939ed0-ee1d-11e6-8d30-c7306bfab3d8.png)
3. it gives message like plugin error uncaught authorization exception
![image](https://cloud.githubusercontent.com/assets/25635574/22734925/848db6ca-ee1d-11e6-9c4f-3401c5a4e411.png)
![image](https://cloud.githubusercontent.com/assets/25635574/22734973/af5b1050-ee1d-11e6-9288-8b7ce9f0ab86.png)

Everything works fine when we use open network.

**Comment by leantk** [comment] 2017-02-08 13:58
Hi @apsuch-cont,

Sorry you're having trouble. Thanks for reporting it. Would you be able to send me a log of the error please? It should help me to see where we are going wrong. Follow the last FAQ at this link for how to get the log: http://java.visualstudio.com/Docs/tools/androidstudio#_frequently-asked-questions-faq
If you don't want to post the log here, feel free to email it to me directly at leantk@microsoft.com

Thanks again,
-Leah

**Comment by b0rke5** [comment] 2017-02-10 14:54
Hi!
The same problem even on open network on a new version.
Version: 1.113.0

After login to TFS no matter if it is Import to TFSC Git/TFSC Preview or checking out from TFSC we get a same RuntimeExc in Android Studio:

17:38:56 Plugin Error: Visual Studio Team Services threw an uncaught RuntimeException. Disable Plugin
17:38:56 RuntimeException: getAuthenticationInfoAsync failed: Could not find any accounts.

![2017-02-10 17_50_40-import project into team services](https://cloud.githubusercontent.com/assets/524281/22830954/7dbfd830-efb9-11e6-818b-3af1a452d55d.png)

**Comment by apsuch-cont** [comment] 2017-02-10 16:51
Hi Leah,
I have shared the log on mail please suggest.

**Comment by leantk** [comment] 2017-02-13 17:42
I'm taking a look at this now. Thanks for sharing the logs. I'll let you know what I find as soon as I can. I apologize for the inconvenience. 

Thanks again,
-Leah

**Comment by leantk** [comment] 2017-02-14 15:03
The "Could not find any accounts" was caused by a server side bug that is now fixed. If you try to authenticate now, you should be able to do so without issue. I'm closing this issue as resolved since I've had verification from @apsuch-cont that it worked. 

@b0rke5 if you are still seeing issues please feel free to reopen this.

**Closed by leantk** 2017-02-14 15:03 UTC
Labels: bug
